apiVersion: v1
kind: Service
metadata:
  name: diving-analytics-service
  labels:
    app: diving-analytics
spec:
  type: LoadBalancer
  selector:
    app: diving-analytics
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
    name: http
